name: Test

on:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Use Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: Install dependencies
        run: |
          bun install

      #      - name: Install Playwright Browsers
      #        run: |
      #          bunx playwright install --with-deps

      - name: Check linting
        run: |
          bun run lint

      - name: Check types
        run: |
          bun run check

      - name: Build
        run: |
          bun run build

      #      - name: Test
      #        run: |
      #          bun run test:headless

      - uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30
